defaults:
  - model: hifigan_generator
  - discriminator: hifigan_discriminator
  - writer: wandb
  - metrics: no_metrics
  - datasets: ljspeech
  - dataloader: default
  - transforms: only_spectrogram
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]
  weight_decay: 0.01
lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.99999
loss_function:
  _target_: src.loss.GeneratorLoss
discriminator_loss_function:
  _target_: src.loss.DiscriminatorLoss
trainer:
  log_step: 50
  n_epochs: 50
  epoch_len: 200
  device_tensors: ["spectrogram", "audio"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: False # if True, will override the previous run with the same name
  monitor: "min test_loss" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  amp_float_type:
    _target_: torch.__dict__.get
    _args_:
      - bfloat16
  # max_grad_norm: 5
  seed: 1
