defaults:
  - model: hifigan_generator
  - metrics: no_metrics
  - datasets: synthesize # we do not want to run inference on training data
  - dataloader: smol_default
  - transforms: generate_spectrogram
  - _self_
inferencer:
  device_tensors: ["spectrogram"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "./checkpoint-epoch100.pth" # path to the pretrained model
text: null
