train:
  get_spectrogram: # special key for getting spectrogram
    _target_: src.transforms.MelSpectrogram
    config:
      _target_: src.transforms.MelSpectrogramConfig
      sr: 22050
      win_length: 1024
      hop_length: 256
      n_fft: 1024
      f_min: 0
      f_max: 8000
      n_mels: 80
      power: 1.0
      pad_value: -11.5129251
      center: False
    normalize_audio: True
inference:
  get_spectrogram:
    _target_: src.transforms.MelSpectrogram
    config:
      _target_: src.transforms.MelSpectrogramConfig
      sr: 22050
      win_length: 1024
      hop_length: 256
      n_fft: 1024
      f_min: 0
      f_max: 8000
      n_mels: 80
      power: 1.0
      pad_value: -11.5129251
      center: False
    normalize_audio: True
